### PR TITLE
Added (hopefully complete) instructions for building Splashkit on Windows.

### PR DESCRIPTION
**Pull request by njsch**
* Updated: ./setting-up-splashkit-dev.md to include much more detailed instructions on how to install on Windows.  Should now clear up a lot of previous ambiguity.

### CODE REVIEW

**Comment by njsch** [comment]
Update: in light of email exchanges, have yet to update dev doc to include build with "Unix Makefiles" explicitly specified rather than Visual Studio or MinGw (only work for x86) and even MSYS Makefiles (that doesn't work either for some reason).

**Comment by njsch** [comment]
Okay @macite, should be good to go now.  Integrated raw HTML with Markdown in the Win instructions to hopefully make it look better as the structure of the nested unordered lists in the ordered one seemed to difficult for md to handle.

**Review by macite — CHANGES_REQUESTED** [review]
Comments look good, but we want to avoid having to include html within the md. If the list wasn't being created correctly check the indentation of the ordered list vs the nested unordered list. The number of spaces that the unordered list is nested will be important.

**Review by hugglesfox — CHANGES_REQUESTED** [review]
Markdown can handle nested lists using indents (usually 2 spaces). For an example:

- List item
  - Nested list item
    - Nested nested list item

The github markdown renderer has ignored the bits of markdown which are inside html tags so things like the fenced code blocks and the hyperlinks aren't rendering. Also it looks like you have missed a closing tag or something as half of the instructions are bold...

I can't fault you for any of this but you may want to fix it up before we merge this PR. If you need any help, please feel free to ask.

Also one more side note, you've included `out/lib/libSplashKitBackend.a` in one of your commits. As this is a compiled binary it shouldn't be committed to the repo.

Otherwise the instructions themselves are looking good!

**EDIT:** Ops sorry Andrew must have replied whilst I was writing out mine... I'll leave this here anyway as it might help.

**Comment by njsch** [comment]
@macite, how do you tell an ordered list to continue after a line break? Indentation doesn't seem to work, unless I just put everything in nested unordered lists?

**Comment by njsch** [comment]
@macite, issues with Markdown should hopefully be fixed - just using all unordered lists now.

**Pull request merged**
