### PR TITLE
NEW: Operator Overloads for point_2d and vector_2d

### PR DESCRIPTION
**Pull request by YT-Sebastian**
Some suggested extensions to point_2d and vector_2d structs. Although there are functions that exist that do the same thing, it feels natural and would be a welcome feature (from my experience with using these heavily) to be able to use operators on these, such as:
point_2d moved_point = pt1 + vt1; 
// where pt1 is a point_2d and vt1 is a vector_2d

### CODE REVIEW

**Comment by YT-Sebastian** [comment]
Not passing the ruby translator. I can't figure out how to solve this because I am not familiar with the parser and what it's doing. Maybe because the declarations live in the type.h file, but the functions are in point_geometry and vector_2d? Would it be better to move the operator overload functions inside types.cpp? Need a bit of help on this one

**Comment by hugglesfox** [comment]
What's currently the main block for this PR as this functionality would be great?

**Comment by macite** [comment]
For this you will need to adjust the translator to be able to generate an appropriate method in the SplashKit interface (generated by the translator) and the various language adapters. A potentially easier option is to add a markup in the code header comments that the translator picks up for a given method to indicate it can be used to create an operator overload in the adapter code. Then the translator can create a call to that method within an operator overload for the client language if that is supported.

**Comment by macite** [comment]
Closing until someone wants to take this challenging task on.

**Pull request closed without merging**
