### PR TITLE
docs: fix broken layout on development setup

### PR DESCRIPTION
**Pull request by tancnle**
This commit fixes issues with code blocks that are not rendered when viewing on Github. As part of this PR, I have also addressed the following items.

- Rename `setting-up-splashkit-dev.md` to `CONTRIBUTING.md` for consistency with OnTrack development.
- Remove duplicate macOS setup instructions on `README.md`.
- Update reference to `CONTRIBUTING.md` on `README.md`.

| Before | After |
|--|--|
|Screen Shot 2022-03-12 at 10 50 10 pm|Screen Shot 2022-03-12 at 10 50 53 pm|

### CODE REVIEW

**Comment by tancnle** [comment]
@macite will love your feedback on this PR 🙏🏼 I will help to enable the dev setup for our teams.

**Comment by RayGuo-ergou** [comment]
> ## Linux
> ### Install prerequisites
> 1. Update your system
>    ```shell
>    sudo apt-get update
>    
>    sudo apt-get upgrade -y
>    ```
> 2. Install the packages
>    ```shell
>    sudo apt-get install -y git build-essential cmake libpng-dev libcurl4-openssl-dev libsdl2-dev libsdl2-mixer-dev libsdl2-gfx-dev libsdl2-image-dev libsdl2-net-dev libsdl2-ttf-dev libmikmod-dev libncurses5-dev libbz2-dev libflac-dev libvorbis-dev libwebp-dev libfreetype6-dev
>    ```
> 
> ### Build & test
> 1. [Create a fork](https://guides.github.com/activities/forking/) of SplashKit.
> 2. Clone the forked repository into your preferred location.
>    ```shell
>    git clone --recursive -j2 https://github.com/<username>/splashkit-core.git
>    ```
> 3. Build the test project:
>    
>    * In a terminal application, go into the cloned directory of your SplashKit
>      fork, and type:
>      ```shell
>      cd projects/cmake
>      cmake .
>      make
>      ```
> 4. Run the test program by executing
>    ```shell
>    cd ../../bin
>    ./sktest
>    ```
> 5. Add features to code in
>    ```shell
>    ./coresdk
>    ```
> 6. Add test code into `coresdk/src/test`. Now you should be good to go.

Hi Tan I think we can add the linux installtion as well.

**Comment by tancnle** [comment]
@RayGuo-ergou  I have added the Linux instruction in [33c4f14](https://github.com/splashkit/splashkit-core/pull/148/commits/33c4f14f3e0e5f6ecf255a23cf0c8639a3586c6e).

**Comment by tancnle** [comment]
@jakerenzella could you kindly review this PR, please? 🙏🏼

**Comment by RayGuo-ergou** [comment]
LGTM

**Comment by jakerenzella** [comment]
@tancnle Just to confirm this is just a formatting fix and no content change? If so looks good :)

**Comment by tancnle** [comment]
> @tancnle Just to confirm this is just a formatting fix and no content change? If so looks good :)

No, it is not just a formatting fix. Additional items:

- Rename `setting-up-splashkit-dev.md` to `CONTRIBUTING.md`
- Remove duplicate macOS setup instructions on `README.md`
- Update reference to `CONTRIBUTING.md` on `README.md`

**Comment by jakerenzella** [comment]
> > @tancnle Just to confirm this is just a formatting fix and no content change? If so looks good :)
> 
> No, it is not just a formatting fix. Additional items:
> 
> * Rename `setting-up-splashkit-dev.md` to `CONTRIBUTING.md`
> * Remove duplicate macOS setup instructions on `README.md`
> * Update reference to `CONTRIBUTING.md` on `README.md`

Yes but no new instructions or content changes? Just a restructuring right? Just checking as I haven't run the instructions. I think this is good to merge - the readability fixes are good and if there are any required changes to actual instructions we can fix up 👍  Nice work all

**Comment by tancnle** [comment]
> Yes but no new instructions or content changes? 

There are new instructions on Linux by @RayGuo-ergou and clean up around prerequisites on macOS (remove `git`, `svn`, `mercurial` and `atom`).

**Comment by macite** [comment]
Thanks @jakerenzella for merging this too :)

**Pull request merged**
